# Generated by Django 2.1 on 2020-11-26 02:29

import S3.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=S3.models.user_directory_path)),
                ('image_caption', models.CharField(default='Photo by demo', max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255, verbose_name='S3 Bucket')),
                ('path', models.FileField(upload_to='', verbose_name='S3 path')),
                ('s3_src', models.CharField(max_length=255, verbose_name='S3 Link')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-id',),
            },
        ),
    ]
